__uri__ = "https://www.arjunsavel.com/PDFs/CV_Savel.pdf"
__author__ = "Arjun B. Savel"
__email__ = "asavel@gmail.com"
__license__ = "MIT"
__version__ = "0.1"
__release__ = "0.1-beta"
__description__ = "Automated CV."
